version: '3.8'

services:
  app:
    image: classroom-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    command: ["./run.sh"]